'use client'

import React, { useEffect } from "react";
import Cover from "./components/Cover";
import Navbar from "./components/Navbar";
import Head from "next/head";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
const index = () => {
  return (
    <>
      <Head>
        <title>CatLabsNFT - NFT Ticketing Platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <ToastContainer
            position="top-center"
            autoClose={5000}
            hideProgressBar={false}
            reverseOrder={false}
            theme="light"
          />
          <Navbar />
          <Cover />
        </div>
      </main>
    </>
  );
};

export default index;
