import { useAddress, useMetamask } from "@thirdweb-dev/react";
import Head from "next/head";
import { ToastContainer} from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import About from "./components/About";
import Benefit from "./components/Benefit";
import Partners from "./components/Partners";
import Hero from "./components/Hero";
import Navbar from "./components/Navbar";
import Faq from "./components/Faq";
import Footer from "./components/Footer";
export default function Home() {
  return (
    <>
      <ToastContainer
        position="top-center"
        autoClose={5000}
        hideProgressBar={false}
        reverseOrder={false}
        theme="light"
      />
      <Head>
        <title>CatLabsNFT - NFT Ticketing Platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-black">
        <Navbar/>
        <Hero/>
        <About/>
        <Benefit/>
        <Partners/>
        <Faq/>
        <Footer/>
      </main>
    </>
  );
}
