"use client";

import React, { useEffect } from "react";
import Head from "next/head";
import About from "./components/About/About";
import Benefit from "./components/Benefit/Benefit";
import Partners from "./components/Partner/Partners";
import Hero from "./components/Hero/Hero";
import Navbar from "./components/Navbar/Navbar";
import Faq from "./components/Faq/Faq";
import Footer from "./components/Footer/Footer";
import Aos from "aos";
export default function Home() {
  useEffect(() => {
    Aos.init();
  }, [])
  return (
    <>
      <Head>
        <title>CatLabsNFT - NFT Ticketing Platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-black">
        <Navbar />
        <Hero />
        <About/>
        <Benefit/>
        <Partners/>
        <Footer/>
      </main>
    </>
  );
}
